### ISSUE TITLE
Change from dec 25 to dec 21

### ISSUE THREAD

**Issue by MV88** [allyoucanmap/timer#25]
We want to know what time is missing till the end of everything

**Comment by dromagnoli** [comment]
+1

**Comment by tdipisa** [comment]
+1 please provide a fix quickly.

**Comment by tdipisa** [comment]
The fix is still missing

**Comment by dromagnoli** [comment]
we are not here ( = non ci siamo)

**Comment by allyoucanmap** [comment]
closed in 1c96afe607cc61850c6ef3d5053959509c5f1b9c
