### ISSUE TITLE
unable to find Villa Scorzi a Calci

### ISSUE THREAD

**Issue by dromagnoli** [allyoucanmap/timer#8]

**Comment by MV88** [comment]
mbecille

**Comment by randomorder** [comment]
Prova a Manate :-)

**Comment by dromagnoli** [comment]
Non compila.

**Comment by randomorder** [comment]
-DskipTests

**Comment by dromagnoli** [comment]
fallisce la build di Jenkins

**Comment by allyoucanmap** [comment]
basta

**Comment by dromagnoli** [comment]
con -DskipTests non va e nemmeno con -DioCane

**Comment by MV88** [comment]
trovato possiamo chiudere la issue

**Comment by MV88** [comment]
http://www.villascorzi.it/it/dove-siamo

**Comment by allyoucanmap** [comment]
@dromagnoli @MV88 @randomorder possiamo considerarla risolta?

**Comment by dromagnoli** [comment]
solo per oggi... ma a partire da 7

**Comment by randomorder** [comment]
Please assign this to @afabiani

**Comment by MV88** [comment]
Era ora

Il ven 10 ago 2018, 09:29 Daniele Romagnoli <notifications@github.com> ha
scritto:
